print("Program starting.")
w1=input("Insert first word: ")
w2=input("Insert second word: ")
print("1st word is",len(w1),"characters long.")
print("2nd word is",len(w2),"characters long.")
print("Words together makes one closed compound '"+w1+w2+"'.")
print("Program ending.")